xgb_features=['ip', 'app', 'device', 'os', 'channel', 
        'app_conversion_rate',
       'app_daily_max', 'app_hourly_std', 'channel_conversion_rate',
       'channel_daily_max', 'channel_hourly_std', 'device_conversion_rate',
       'device_daily_max', 'device_hourly_std', 'os_conversion_rate',
       'os_daily_max', 'os_hourly_std', 'ip_conversion_rate', 'ip_daily_max',
       'ip_hourly_std', 'app_channel_conversion_rate', 'app_channel_daily_max',
       'app_channel_hourly_std', 'app_device_conversion_rate',
       'app_device_daily_max', 'app_device_hourly_std',
       'app_os_conversion_rate', 'app_os_daily_max', 'app_os_hourly_std',
       'app_ip_conversion_rate', 'app_ip_daily_max', 'app_ip_hourly_std',
       'channel_device_conversion_rate', 'channel_device_daily_max',
       'channel_device_hourly_std', 'channel_os_conversion_rate',
       'channel_os_daily_max', 'channel_os_hourly_std',
       'channel_ip_conversion_rate', 'channel_ip_daily_max',
       'channel_ip_hourly_std', 'device_os_conversion_rate',
       'device_os_daily_max', 'device_os_hourly_std',
       'device_ip_conversion_rate', 'device_ip_daily_max',
       'device_ip_hourly_std', 'os_ip_conversion_rate', 'os_ip_daily_max',
       'os_ip_hourly_std']