xgb_features=['app', 'channel', 'click_time_day', 'click_time_hour', 'device', 'ip',
       'is_attributed', 'os', 'app_hourly_count', 'app_yes_conversion_rate',
       'app_is_new', 'channel_hourly_count', 'channel_yes_conversion_rate',
       'channel_is_new', 'device_hourly_count', 'device_yes_conversion_rate',
       'device_is_new', 'os_hourly_count', 'os_yes_conversion_rate',
       'os_is_new', 'app_channel_hourly_count',
       'app_channel_yes_conversion_rate', 'app_channel_is_new',
       'app_device_hourly_count', 'app_device_yes_conversion_rate',
       'app_device_is_new', 'app_os_hourly_count',
       'app_os_yes_conversion_rate', 'app_os_is_new', 'app_ip_hourly_count',
       'app_ip_yes_conversion_rate', 'app_ip_is_new',
       'channel_device_hourly_count', 'channel_device_yes_conversion_rate',
       'channel_device_is_new', 'channel_os_hourly_count',
       'channel_os_yes_conversion_rate', 'channel_os_is_new',
       'channel_ip_hourly_count', 'channel_ip_yes_conversion_rate',
       'channel_ip_is_new', 'device_os_hourly_count',
       'device_os_yes_conversion_rate', 'device_os_is_new',
       'device_ip_hourly_count', 'device_ip_yes_conversion_rate',
       'device_ip_is_new', 'os_ip_hourly_count', 'os_ip_yes_conversion_rate',
       'os_ip_is_new']

rfr_features=['app', 'channel', 'click_time_day', 'click_time_hour', 'device', 'ip',
       'is_attributed', 'os', 'app_hourly_count', 'app_yes_conversion_rate',
       'app_is_new', 'channel_hourly_count', 'channel_yes_conversion_rate',
       'channel_is_new', 'device_hourly_count', 'device_yes_conversion_rate',
       'device_is_new', 'os_hourly_count', 'os_yes_conversion_rate',
       'os_is_new', 'app_channel_hourly_count',
       'app_channel_yes_conversion_rate', 'app_channel_is_new',
       'app_device_hourly_count', 'app_device_yes_conversion_rate',
       'app_device_is_new', 'app_os_hourly_count',
       'app_os_yes_conversion_rate', 'app_os_is_new', 'app_ip_hourly_count',
       'app_ip_yes_conversion_rate', 'app_ip_is_new',
       'channel_device_hourly_count', 'channel_device_yes_conversion_rate',
       'channel_device_is_new', 'channel_os_hourly_count',
       'channel_os_yes_conversion_rate', 'channel_os_is_new',
       'channel_ip_hourly_count', 'channel_ip_yes_conversion_rate',
       'channel_ip_is_new', 'device_os_hourly_count',
       'device_os_yes_conversion_rate', 'device_os_is_new',
       'device_ip_hourly_count', 'device_ip_yes_conversion_rate',
       'device_ip_is_new', 'os_ip_hourly_count', 'os_ip_yes_conversion_rate',
       'os_ip_is_new']
